spring:
  datasource: 
    url: jdbc:sqlserver://${azureservername}.database.windows.net:1433;database=${azuredatabasename};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30
    username: ${username}
    password: ${password}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: SQL_SERVER

okta:
  oauth2:
    client-id: 0oagpohm2l2G3DJ2u5d7
    issuer: https://dev-24319924.okta.com/oauth2/default

stripe:
  key:
    secret: ${stripesecret}

application:
  security:
    jwt:
      secret-key: ${jwtkey}
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
